### ISSUE TITLE
Cannot call method 'writeLine' of undefined

### ISSUE THREAD

**Issue by fsmanuel** [simplabs/ember-cli-simple-auth-torii#8] opened 2015-03-12 09:49 UTC
```
version: 0.2.0
node: 0.10.33
npm: 2.7.0
```

When i `ember install:addon ember-cli-simple-auth-torii` i get the following error:

```
TypeError: Cannot call method 'writeLine' of undefined
    at AddonDiscovery.<anonymous> (/Users/manuel/Code/customers/ag-prop/bochum/timelines/node_modules/ember-cli/lib/models/addon-discovery.js:109:22)
    at Array.map (native)
    at AddonDiscovery.discoverFromDependencies (/Users/manuel/Code/customers/ag-prop/bochum/timelines/node_modules/ember-cli/lib/models/addon-discovery.js:94:68)
    at AddonDiscovery.discoverChildAddons (/Users/manuel/Code/customers/ag-prop/bochum/timelines/node_modules/ember-cli/lib/models/addon-discovery.js:61:31)
    at Class.Addon.discoverAddons (/Users/manuel/Code/customers/ag-prop/bochum/timelines/node_modules/ember-cli/lib/models/addon.js:172:40)
    at Class.Addon.initializeAddons (/Users/manuel/Code/customers/ag-prop/bochum/timelines/node_modules/ember-cli/lib/models/addon.js:188:8)
    at setupRegistryForEachAddon (/Users/manuel/Code/customers/ag-prop/bochum/timelines/node_modules/ember-cli/lib/preprocessors.js:18:10)
    at Object.module.exports.setupRegistry (/Users/manuel/Code/customers/ag-prop/bochum/timelines/node_modules/ember-cli/lib/preprocessors.js:46:3)
    at Class.Addon (/Users/manuel/Code/customers/ag-prop/bochum/timelines/node_modules/ember-cli/lib/models/addon.js:83:5)
    at new Class (/Users/manuel/Code/customers/ag-prop/bochum/timelines/node_modules/ember-cli/node_modules/core-object/core-object.js:16:17)
```

**Comment by marcoow** [comment] 2015-03-12 09:50
duplicate of #7

**Closed by marcoow** 2015-03-12 09:50 UTC

**Comment by fsmanuel** [comment] 2015-03-12 10:31
argh, should have taken a look at the closed issues.

**Comment by timini** [comment] 2015-03-13 10:46
You have close them both.. But is it fixed?

**Comment by h55nick** [comment] 2015-03-19 16:46
take a look at the bottom of #7, pointing ember-cli to master currently gets it done until it hits a release.
